fix: typization in packsApi and cardsApi
KarolinaEsepenok/cards pull request #52
Opened 2023-01-22 19:03 UTC by Oldeg

feat: sortHelper function

2023-01-22 19:24 UTC, MorozovaAN requested changes

2023-01-22 19:24 UTC, MorozovaAN commented on src/common/utils/sortHelper.ts
> +  dispatch: Dispatch,
у диспатча есть типизация: AppDispatchType

2023-01-22 19:24 UTC, MorozovaAN commented on src/features/packs/packsList/PacksList.tsx
> +  const universalSort = (m1: sortingPacksMethods, m2: sortingPacksMethods) => {
получается два раза sortingPacksMethods нужно передавать.
А вот если так написать, это не сработает?:

export const sortHelper = (
  dispatch: Dispatch,
  m1: sortingPacksMethods,
  m2: sortingPacksMethods
) => {
  sortingPacksMethods  === m1 ? dispatch(setSort(sortingPacksMethods.m1)) : dispatch(setSort(sortingPacksMethods.m2))
}

и вот так вызвать: universalSort(desName, ascName)

2023-01-22 20:06 UTC, Oldeg commented on src/features/packs/packsList/PacksList.tsx
> +  const universalSort = (m1: sortingPacksMethods, m2: sortingPacksMethods) => {
не,так точно не будет работать

2023-01-23 13:30 UTC, MorozovaAN approved these changes

2023-01-23 13:31 UTC, merged